---
- name: Install Docker and Docker Compose on Ubuntu 24.04
  hosts: all
  gather_facts: yes
  tasks:
    - name: Update apt cache and upgrade system
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Create directory for APT keys
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Ensure Docker GPG key permissions
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker.list
        state: present

    - name: Install Docker Engine and Docker Compose
      ansible.builtin.apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest

    - name: Verify Docker installation
      ansible.builtin.command: docker --version
      register: docker_version

    - name: Verify Docker Compose installation
      ansible.builtin.command: docker compose version
      register: compose_version

    - name: Display Docker and Docker Compose versions
      ansible.builtin.debug:
        msg: |
          Docker version: {{ docker_version.stdout }}
          Docker Compose version: {{ compose_version.stdout }}